# Generated by Django 5.1.4 on 2025-06-30 13:54

import utilisateurs.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='private_key',
            field=utilisateurs.fields.EncryptedBinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
