# Generated by Django 5.1.4 on 2025-06-10 04:09

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuser',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='basicuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region='SN'),
        ),
        migrations.AddField(
            model_name='basicuser',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='basicuser',
            name='two_factor_method',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
