# Generated by Django 5.1.4 on 2025-07-01 14:04

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_doctor_private_key_doctor_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region='SN', unique=True),
        ),
    ]
