# Generated by Django 5.1.4 on 2025-07-03 12:25

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_alter_basicuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='SN', unique=True),
        ),
    ]
