# Generated by Django 5.2.4 on 2025-07-06 04:07

import django.core.validators
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_alter_basicuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuser',
            name='email_hash',
            field=models.CharField(default='', editable=False, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='licence_number_hash',
            field=models.CharField(default='', editable=False, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='licence_number_hash',
            field=models.CharField(default='', editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='licence_number',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='licence_number',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
