# Generated by Django 5.2.4 on 2025-07-10 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_basicuser_email_hash_doctor_licence_number_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicuser',
            name='email_hash',
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
