# Generated by Django 5.1.4 on 2025-06-30 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnance', '0001_initial'),
        ('utilisateurs', '0002_doctor_private_key_doctor_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordonnance_as_doctor', to='utilisateurs.doctor'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordonnance_as_patient', to='utilisateurs.patient'),
        ),
    ]
