# Generated by Django 5.2.4 on 2025-07-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnance', '0003_remove_ordonnance_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordonnance',
            old_name='patient_date_naissance',
            new_name='patient_date_birth',
        ),
        migrations.RenameField(
            model_name='ordonnance',
            old_name='patient_nom',
            new_name='patient_last_name',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='patient_prenom',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='patient_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
