# Generated by Django 5.2.4 on 2025-07-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnance', '0004_rename_patient_date_naissance_ordonnance_patient_date_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='access_code',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
