"""
Django settings for ordosafe project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from cryptography.fernet import Fernet

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'utilisateurs', #integrate users application
    'ordonnance', #integrate prescription application
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_otp', # 2FA modules
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'phonenumber_field', #phone field (compulsory)
    'audit.apps.AuditConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'utilisateurs.middleware.LoginAttemptMiddleware',
]

ROOT_URLCONF = 'ordosafe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
           BASE_DIR / 'ordonnance' / 'templates',
           BASE_DIR / 'utilisateurs' / 'templates', 
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ordosafe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4'
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Authentification configuration
AUTH_USER_MODEL = 'utilisateurs.BasicUser'
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']


# CYPHER METHOD
FERNET_KEY = config('FERNET_KEY')

# Anti Brute Force Configuration
LOGIN_ATTEMPTS_LIMIT = config('LOGIN_ATTEMPTS_LIMIT', default=5, cast=int)
LOGIN_LOCKOUT_DURATION = config('LOGIN_LOCKOUT_DURATION', default=60, cast=int)

# Email 2FA Configuration
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = config('EMAIL_HOST')
#EMAIL_PORT = config('EMAIL_PORT')
#EMAIL_USE_TLS = config('EMAIL_USE_TLS')
#EMAIL_HOST_USER = config('EMAIL_HOST_USER')
#EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

# Sms 2FA Configuration
#TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID')
#TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN')
#TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER')

# Session configuration
SESSION_COOKIE_AGE = 900
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Logs configuration for audit purpose (saved locally on a logs directory)
# Création du dossier logs
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'medical': {
            'format': '{asctime} [MEDICAL] {message}',
            'style': '{',
        },
        'security': {
            'format': '{asctime} [SECURITY] {message}',
            'style': '{',
        }
    },
    'handlers': {
        # For medical audit content
        'medical_audit': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'medical_audit.log'),
            'formatter': 'medical',
            'maxBytes': 50 * 1024 * 1024,
            'backupCount': 20,
        },
        # For security audit content
        'security_audit': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'security.log'),
            'formatter': 'security',
            'maxBytes': 20 * 1024 * 1024,
            'backupCount': 15,
        },
    },
    'loggers': {
        # Medical logs
        'medical.audit': {
            'handlers': ['medical_audit'] + (['console'] if DEBUG else []),
            'level': 'INFO',
            'propagate': False,
        },
        # Logs secure
        'security.audit': {
            'handlers': ['security_audit'] + (['console'] if DEBUG else []),
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


if not DEBUG:
    LOGGING['loggers']['django'] = {
        'handlers': [],
        'level': 'CRITICAL',
        'propagate': False,
    }
