# Generated by Django 5.1.4 on 2025-06-22 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('login_failed', 'Échec de connexion'), ('logout', 'Déconnexion'), ('2fa_success', '2FA réussie'), ('2fa_failed', '2FA échouée'), ('password_change', 'Changement de mot de passe'), ('user_creation', 'Création de compte'), ('profile_update', 'Mise à jour du profil'), ('security_change', 'Modification de sécurité'), ('ordonnance_creation', 'Création ordonnance'), ('ordonnance_modification', 'Modification ordonnance'), ('ordonnance_validation', 'Validation ordonnance'), ('ordonnance_annulation', 'Annulation ordonnance')], max_length=50, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Entrée de journal',
                'verbose_name_plural': 'Journal des audits',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx')],
            },
        ),
    ]
